### ISSUE TITLE
Feature request: Sensor to say when backup is in progress

### ISSUE THREAD

**Issue by mf-social** [sabeechen/hassio-google-drive-backup#134]
Hi,

This addon creates a couple of sensors already, but I could really do with one more, pretty please..

At the point when the log says this: "Requesting a new snapshot" I could do with a binary sensor turning on, that could then turn back off when the log gets to "Snapshot finished".

Basically because I have my snapshots set to auto-doobery at 4.30am, but I also have a watchdog that monitors my system for high CPU/RAM use and sends me a notification.  The snapshot creation triggers the alarm, sometimes a couple of times.

I could condition it not to activate whilst the binary sensor was true, because it would be expected behaviour.

For your consideration.

**Comment by mf-social** [comment]
If the sensor went true a short time before requesting the new snapshot, people could implement a plausible workaround to #121 too, by setting an automation to shutdown the relevant addons, then wait_template the sensor going off and restart them  🙂

**Comment by sabeechen** [comment]
Thanks for explaining how you would use the feature, that helps me figure out how best to help.  I think you could accomplish what you're trying to do with a Template sensor because sensor.snapshot_backup always lists the 'Pending' snapshot last.  In fact, this kind of thing is the whole reason I expose that sensor!  The template binary_sensor below will be True when a snapshot is being created by the addon and False otherwise.
```yaml
binary_sensor:
  - platform: template
    sensors:
      snapshot_in_progress:
        friendly_name: 'Snapshot in Progress'
        value_template: >-
          {{ state_attr('sensor.snapshot_backup', 'snapshots')[-1]['state'] == 'Pending' }}
```
I tested it on one of my dev instances to make sure it works.  It seems to work the way an additional sensor would work if I ever created it.
