### ISSUE TITLE
Upload By calling service

### ISSUE THREAD

**Issue by sagitt** [sabeechen/hassio-google-drive-backup#142]
is possible to execute the sync\upload calling a service instead automatically?

if not is possible add  this?

**Comment by sabeechen** [comment]
The addon basically just calls Hass.io's snapshot service with and then makes sure to sync anything it can find to Google Drive, so if you create an automation that triggers a snapshot (or make one manually) the add-on will sync it to Google Drive as if the addon had created it.  For example you could create a daily snapshot with an automation like this:
```yaml
- alias: Daily snapshot
  description: 'Create a snapshot every day at 9am'
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - data:
      name: Daily snapshot
    service: hassio.snapshot_full
```

The addon will notice when the snapshot is finished and sync it to Google Drive.  If for some reason the addon doesn't notice, it will check for new ones anyway every hour and sync if necessary.
  
Note that this approach has the downside that:
- You have to provide the snapshot name (though you could template it to whatever you want)
- If you only do partial snapshots, you'll have to call hassio.snapshot_partial instead and full specify which components should be included.  Ask if you'd like help figuring out the arguments for this, its kind of complicated.
