### ISSUE TITLE
`supervisor-2021.02.5` has made configuration difficult

### ISSUE THREAD

**Issue by mdegat01** [sabeechen/hassio-google-drive-backup#346]
`supervisor-2021.02.5` seems to have significantly changed the add-on configuration experience. It now presents all configuration options as a generated form unless the configuration includes lists (since it can't handle that). This now causes this add-on to display an absolutely massive list of configuration options, nearly all of which are already configurable in the add-on UI.

It also doesn't seem to be parsing booleans correctly? For instance I see this in the configuration UI for the add-on:
<img width="1040" alt="Screen Shot 2021-02-08 at 10 44 57 PM" src="https://user-images.githubusercontent.com/2037026/107312829-4f4fcf80-6a5f-11eb-9982-b2b174ce67c3.png">
But as you can see below, I have both the sensors turned on in the add-on UI and can confirm they definitely appears in my list of entities:
<img width="731" alt="Screen Shot 2021-02-08 at 10 46 14 PM" src="https://user-images.githubusercontent.com/2037026/107312934-8d4cf380-6a5f-11eb-8d20-c503e8b459e5.png">
<img width="829" alt="Screen Shot 2021-02-08 at 10 47 45 PM" src="https://user-images.githubusercontent.com/2037026/107312986-ae154900-6a5f-11eb-9edb-2f9bcbf2164d.png">

Anyway I really don't know the implications of this change. I'm honestly afraid to modify anything in the configuration panel now because I don't really trust that its correctly pulling in the options I configured in the UI and I don't want to mess up my working configuration. I just wanted to make sure you were aware this happened as it now looks quite overwhelming for new users. And yea if existing users have to change any of the options not exposed in the UI it may be quite difficult now.

**Comment by sabeechen** [comment]
Oh good lord, this is terrible.

The reason some values appear different between the addon setting UI and the supervisor UI is that the supervisor UI interprets "not present" as false while the addon interprets not present as "default", which may be true or false depending on the option.  For example enable_snapshot_stale_sensor is defaulted to true when not specified, but expose_extra_server is defaulted to false.

So setting a config option in the supervisor's editor should still work fine, you just might be setting it to the value it already was.  I'd still use the addon's editor though, I'm not sure what the supervisor

I'm going to need to do some digging to see what this breaks, or if I can somehow opt out of this change for the addon.  I haven't noticed problems on my instance after updating, but definitely the config UI in the supervisor is terrible now.

**Comment by mdegat01** [comment]
Well I did notice that any of my addons with a list in their configuration didn't change at all. So if there's not an explicit opt-out option then a temporary fix might be to introduce a config option that accepts an array just to force it back to YAML form. Although I imagine eventually that will be converted to UI as well.

And yea everything works fine through the update but changing things might have negative consequences. Like what you said about booleans completely makes sense but now I wonder what else it's doing that too. Like if I go to the configuration options and I say "edit in YAML" here's what it shows me:
```yaml
max_snapshots_in_hassio: 12
max_snapshots_in_google_drive: 12
days_between_snapshots: 1
use_ssl: true
snapshot_time_of_day: '04:30'
snapshot_password: '< password >'
snapshot_name: '{type} Snapshot {version_ha} {date} -MariaDB'
notify_for_stale_snapshots: false
send_error_reports: true
generational_days: 4
generational_weeks: 4
generational_months: 3
alternate_dns_servers: '94.140.14.14,94.140.15.15'
exclude_addons: core_mariadb
background_color: '#141414'
accent_color: '#2980b9'
certfile: ''
keyfile: ''
generational_day_of_week: ''
exclude_folders: ''
stop_addons: ''
drive_ipv4: ''
hassio_url: ''
home_assistant_url: ''
hassio_header: ''
drive_url: ''
authenticate_url: ''
refresh_url: ''
drive_refresh_url: ''
drive_token_url: ''
drive_authorize_url: ''
choose_folder_url: ''
error_report_url: ''
drive_host_name: ''
save_drive_creds_path: ''
stop_addon_state_path: ''
folder_file_path: ''
config_file_path: ''
retained_file_path: ''
secrets_file_path: ''
id_file_path: ''
backup_directory_path: ''
credentials_file_path: ''
ingress_token_file_path: ''
default_drive_client_id: ''
default_drive_client_secret: ''
drive_picker_api_key: ''
server_project_id: ''
```
I didn't touch any of the config options set to `''` so if I save like this will it actually be ok? Or for these will it go from "config option not set mode" to assuming I did set those config values and set it to `''` for some reason?

I don't actually need to set anything in here right now so this isn't an urgent issue for me. I just noticed one of my other addons changed so I started looking around to see what else happened. I was a little confused why it says `use_ssl: true` since I use Ingress but nothing seems to be broken so I am planning to ignore that for now. I mostly just figured you would want to know and didn't see another option issue on the topic.
