### ISSUE TITLE
Feature Request: Add a sensor / event to indicate if the snapshot is running /started / finished

### ISSUE THREAD

**Issue by kelvinng1** [sabeechen/hassio-google-drive-backup#385]
Use Case:

I have an automation to reboot HASS host regularly, after the snapshot. Occasionally, the reboot may start before the snapshot finished due to extended snapshot duration, and this often cause problems.

Adding a sensor allows me to put it into the condition (sensor state) of my automation, so that the reboot will only happen if the snapshot is not running.

By adding an event during the start / stop of the snapshot, I can make use of the snapshot stop event to trigger my reboot.

**Comment by sabeechen** [comment]
I recently helped someone else create a notification when a new snapshot is uploaded that I think you could adapt to accomplish this:

* First create a template sensor in configuration.yaml that stores the name of the latest backed up snapshot:
  ```yaml
  sensor:
  - platform: template
    sensors:
      latest_backup:
        value_template: >-
          {% set found=namespace(snapshot=None,time=0) %}
          {% for snapshot in state_attr('sensor.snapshot_backup', 'snapshots') %}
            {% if as_timestamp(snapshot.date) > found.time and snapshot.state == "Backed Up" %}
              {% set found.time = as_timestamp(snapshot.date) %}
              {% set found.snapshot = snapshot %}
            {% endif %}
          {% endfor %}
          {{ found.snapshot.name }} ({{ found.snapshot.size}})
  ```
* Then make an automation that sends you a notification when the most recently backed up name changes, ignoring when the state changes from an unknown value (when HA starts up initially).
  ```yaml
  - alias: Notify for a new backup
    trigger:
    - platform: state
      entity_id: sensor.latest_backup
    condition:
    - condition: template
      value_template: '{{trigger.from_state.state != None and trigger.from_state.state
      != '''' and trigger.from_state.state != ''unavailable''}}'
    action:
    - service: notify.your_notification_target
      data:
        title: New Snapshot
        message: Created and backed up {{states('sensor.latest_backup')}}
  ```

Note that this will also trigger an erroneous notification if you delete the latest snapshot and it would also be possible to create this using only an automation.  The logic for solving these problems would be pretty complicated.

You should be able to change the service action from notify.X to whatever you're using to trigger your reboot.
