### ISSUE TITLE
Day of the week schedule not set days between

### ISSUE THREAD

**Issue by spjt1502** [sabeechen/hassio-google-drive-backup#405]
Hi would it be possible to choose the day of the week to complete the snapshot rather than number of days between snapshots, where in the past I have done partial or full snapshots outside of the scheduled 7 days this then shifts the day that the next snapshot is taken this is unhelpful as I have a prerequisite task schedule on another machine that is done based on time and days of the week with the mismatch of tasks happening it can cause issue with the size of the snapshots

**Comment by sabeechen** [comment]
Many people want many different schemes for determining when to take snapshots, but in practice I can't support them all without making configuration of the addon very complicated.  You can accomplish more-or-less any logic for when to take snapshots by moving the responsibility for creating snapshots to Home Assistant and configuring this addon to just back them up to Google Drive and delete old ones.  You'd do this by:
 - Setting ```Days Between Snapshots``` to ```0``` in the addon.  This tells it to never create snapshots.
 - Configuring Home Assistant to create a snapshot once per week.  For example this automation *should* call the supervisor's snapshot service once per week on monday at 5 am (I haven't tested it).
    ``` yaml
    - alias: Snapshot on Monday
      description: Take Snapshot on Monday
      trigger:
      - platform: time
        at: 05:00
      condition:
      - alias: Only on Monday
        condition: time
        before: 06:00:00
        weekday:
        - mon
      action:
      - service: hassio.snapshot_full
        data:
          name: Snapshot created by Home Assistant
    ```
This has some downsides worth noting:
 - The snapshot will not be retried it if it fails.
 - The addon will not complain if snapshots get stale (eg if they fail repeatedly)
 - You will need to script the snapshot name yourself (using a template) if you don't want all the snapshots to have the same name.
 - Creating partial snapshots is complicated (I can provide detail if you need guidance).

An alternative option to all this is to configure the addon to "Ignore other snapshots" (see the settings UI).  This will cause any one-off snapshots you create outside the addon to be ignored.  It won't back them up to Google Drive or clean them up automatically, but it will also prevent them from interrupting your normal weekly schedule.
