### ISSUE TITLE
The recorder backlog queue reached the maximum size of 40000 events

### ISSUE THREAD

**Issue by agmuz** [sabeechen/hassio-google-drive-backup#762]
while backing up HA loses sensors, restart helps. Since I could not find anything about this error in the docs and Google didn’t help either, I did a reboot and now the energy dashboard is picking up data again.

Do I have to reboot HASS OS everytime this error appears?

**Comment by sabeechen** [comment]
Sorry its taken me a while to get back to you, I've been out of town.

I believe the database has to be paused to get backed up, if you have a very large database and it takes a very long time to get backed up I could image the recorder getting backed up.  Does the problem persist after the backup completes?

It would be helpful if you use the add-on's bug reporting feature, in the add-on web-ui go to "Actions" > "Report a Bug", since it lets me see what configuration you're using.  If you build the report while the problem is happening it will also show log message that could be of use.

**Comment by rechin304** [comment]
I have same issue. Indeed DB is huge.

**Comment by rechin304** [comment]
###### Description:
```
The recorder backlog queue reached the maximum size of 40000 events and energy dashboard only works after HA restart.
```

 Addon version: `0.109.2`
 Home Assistant Version: `2023.1.0`
 Supervisor Version: `2022.12.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.4`
 Docker Version: `20.10.19`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2023-01-06T05:28:09.998045+00:00`
 Timezone: `Europe/Bucharest`
 Failure Time: `2023-01-05T05:34:33.543846+00:00`
 Last Good Sync: `2023-01-06T04:00:07.833677+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-01-06T02:00:00Z",
        "max": 0,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 1,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "488.6 MB",
        "free_space": "76.0 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-01-05T02:00:02Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "redacted",
        "size": "26.9 GB",
        "ignored_size": "0.0 B",
        "free_space": "29.0 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 0,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_NAME": "REDACTED",
    "Setting.BACKUP_TIME_OF_DAY": "04:00",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.MAX_SYNC_INTERVAL_SECONDS": 7200.0
}
 ```
 ###### Addon Logs:
 ```
 01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory changed
01-06 07:28:09 DEBUG [backup.worker.watcher] Backup directory modified event
 ```
 ###### Supervisor Logs:
 ```
 [32m23-01-06 07:10:21 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m23-01-06 07:10:21 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[33m23-01-06 07:12:07 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m23-01-06 07:12:08 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m23-01-06 07:16:35 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done[0m
[32m23-01-06 07:16:35 INFO (MainThread) [supervisor.backups.manager] Backing up b4ed1c61 store folders[0m
[32m23-01-06 07:16:35 INFO (SyncWorker_6) [supervisor.backups.backup] Backing up folder share[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_6) [supervisor.backups.backup] Backup folder share done[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_3) [supervisor.backups.backup] Backing up folder addons/local[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_3) [supervisor.backups.backup] Backup folder addons/local done[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_7) [supervisor.backups.backup] Backing up folder ssl[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_7) [supervisor.backups.backup] Backup folder ssl done[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_1) [supervisor.backups.backup] Backing up folder media[0m
[32m23-01-06 07:16:36 INFO (SyncWorker_1) [supervisor.backups.backup] Backup folder media done[0m
[33m23-01-06 07:17:13 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m23-01-06 07:17:13 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m23-01-06 07:19:05 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not WSMsgType.TEXT[0m
[32m23-01-06 07:19:05 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m
[32m23-01-06 07:19:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m23-01-06 07:19:31 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m23-01-06 07:19:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[33m23-01-06 07:22:17 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m23-01-06 07:22:17 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m23-01-06 07:25:07 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m23-01-06 07:27:21 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m23-01-06 07:27:21 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m23-01-06 07:28:03 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not WSMsgType.TEXT[0m
[32m23-01-06 07:28:03 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m
[32m23-01-06 07:28:10 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/config/custom_components/nuki_ng/sensor.py", line 220, in extra_state_attributes
    "timestamp": datetime.fromisoformat(timestamp) if not None else None,
TypeError: fromisoformat: argument must be str[0m
[31m2023-01-06 07:22:45.185 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/nuki_ng/sensor.py", line 98, in state
    return self.native_value
  File "/config/custom_components/nuki_ng/sensor.py", line 94, in native_value
    return self.data.get("bridge_info", {}).get("rssi")
AttributeError: 'NoneType' object has no attribute 'get'[0m
[31m2023-01-06 07:28:00.944 ERROR (MainThread) [frontend.js.latest.202212131] https://etaj.cf/frontend_latest/0f91a437.js:256:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')[0m
[31m2023-01-06 07:28:02.736 ERROR (MainThread) [frontend.js.latest.202212131] https://etaj.cf/frontend_latest/0f91a437.js:256:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')[0m
[31m2023-01-06 07:28:02.738 ERROR (MainThread) [frontend.js.latest.202212131] https://etaj.cf/frontend_latest/0f91a437.js:256:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')[0m
[31m2023-01-06 07:28:04.146 ERROR (MainThread) [frontend.js.latest.202212131] https://etaj.cf/frontend_latest/0f91a437.js:256:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')[0m
[31m2023-01-06 07:28:04.299 ERROR (MainThread) [frontend.js.latest.202212131] https://etaj.cf/frontend_latest/0f91a437.js:256:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')[0m

 ```

**Comment by dbrb2** [comment]
I have been seeing this as well - one "solution" is to schedule a system restart after every backup, but it would be fantastic were this not required

**Comment by sabeechen** [comment]
If you have a very large database, I'm not sure if this can be avoided.  [IIUC](https://github.com/home-assistant/addons/blob/master/mariadb/config.yaml#L14) Home Assistant needs to lock the database during a backup to ensure it gets a consistent copy.   I suspect thats whats causes the recorder backlog, its waiting for the database to come back online for writes.  Id further suspect that the system stalls, hangs, or becomes non-responsive for a time after the backup because its attempting to commit 40k writes at once to clear the backlog.  Since the backlog is full for some time I'd guess it just drops any more events which could break history-sensitive components like the energy dashboard.  This is just speculation, but it makes sense.

IMHO, the database has _always_ been Home Assistant's most troubling feature.  It fills up in a way that confuses new users, and it just stores so much event history an an incredibly inefficient format that hardly anyone uses.  As soon as you have a few hundred entities it needs to be babied to keep the system running.  There are a couple ways I can think of to "sort-of-solve" this.  None of them are great but its worth considering:

- Use a guide [like this one](https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795) to keep the state and event history smaller.  If you're like me, then you have a bunch of frequently updated sensors that you don't actually need history on that gum up the works.
- Exclude the database from backups.  Obviously not ideal, but for many it is a reasonable compromise.
- Use [traditional backup tools](https://mariadb.com/kb/en/backup-and-restore-overview/) to backup the database separately.  The way Home Assistant backs things up (just copying the files offline) isn't how MariaDB is "supposed" to be backed up and there isn't any reason MariaDB's existing toolchain couldn't do the job.  This would require an extra step to seed the database when you restore, though.

In any case I'm not sure if there is another way I can help with this, so I'm going to close this issue for now.  If you think there is something I can do on my side of the addon to make things work better for you, or I'm misunderstanding whats going wrong, please let me know and I'll do what I can.

**Comment by rechin304** [comment]
Thanks for suggestions, this is exactly what I did 2 days ago and I no longer see the issue and Energy tab is now again working as was before.

**Comment by danielbrunt57** [comment]
> Thanks for suggestions, this is exactly what I did 2 days ago and I no longer see the issue and Energy tab is now again working as was before.

Which suggestion(s) did you use?

**Comment by rechin304** [comment]
I did review entities and remove some from logs to keep the state and event history smaller.

**Comment by danielbrunt57** [comment]
Here is my new recorder: settings:
```
recorder:
  db_url: !secret mariadb_url
  db_retry_wait: 5
  purge_keep_days: 7
  include:
    entities:
      - sensor.circuit_11_power
    domains:
      - automation
      - binary_sensor
      - climate
      - cover
      - device_tracker
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - input_text
      - light
      - lock
      - media_player
      - person
      - sensor
      - switch
  exclude:
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop      
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync
    entities:
      - sensor.insteon_groups
      - sensor.home_assistant_v2_db
      - sensor.last_active
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.mariadb_database_size
      - sensor.processor_use
    entity_globs:
    # Emporiavue
      - sensor.dryer*
      - sensor.microwave*
      - sensor.washer*
      - sensor.furnace*
      - sensor.range*
      - sensor.emporia_*
     # Others
      - sensor.*_battery
      - sensor.*_node_status
      - sensor.*_voltage
      - sensor.*_power
      - sensor.*_rx
      - sensor.*_tx
      - sensor.*_uptime
      - sensor.browser_mod*
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.hass_agent*
      - sensor.internet*
      - sensor.load_*
      - sensor.memory_*
      - sensor.processor_*
      - sensor.sun*
      - sensor.time*
      - sensor.uptime*
      - sensor.weather*
```
MariaDB is still decreasing...
![image](https://user-images.githubusercontent.com/49846893/215731445-417e8c0b-7f4b-4152-a43c-ca72b3b18e95.png)
