### ISSUE TITLE
[Request] Differentiate Generational Types

### ISSUE THREAD

**Issue by martoq** [sabeechen/hassio-google-drive-backup#770]
I'd like to be able to differentiate my generational backup types.  For example my daily backups I don't need the entire system backed up, I'd rather just do a partial backup on specific things, ie a partial backup.  For example just core and node-red.  But then on my weekly, monthly and yearly I'd like to do a FULL backup.  This would greatly reduce my backup sizes as my dailies are taking up space backing up items that don't really need to be backed up.

**Comment by sabeechen** [comment]
This is a cool idea, and I think a small but passionate number of people would benefit greatly from it.  Despite that I'm not going to implement it for two reasons:
1. I get a lot of requests for configurable backup schemes, and I'd like to try to keep configuration of the addon relatively simple.  If I implemented everything asked for the settings would be a mess, figuring out how they all interact would be complicated, and I would make a lot of mistakes implementing it.  The maintenance burden of this addon is something I have to consider with every feature I add.  Its already kind of a mess.
2. Its possible for you to do something very close to this with just a little extra logic on your side, here is how:
   - Make sure you have "Ignore other backups" set to false in your setting ("Ignore upgrade backups" can still be turned on)
   - Lets say you have your generational backups configured to be kept on monday weekly and the first day of the month monthly.   Add the following automation:
     ```yaml
     alias: Create a full Backup Periodically
     description: "Creates a full backup sometimes that overrides the regular partial backup"
     
     # Evaluate this automation every day at 05:00 AM.
     # This should be before you have the addon configured to create a partial backup.
     trigger:
       - platform: time
         at: "05:00:00"

     # Only continue if its the first day of the week of first day of the month
     condition:
       - condition: template
         value_template: "{{ now().day == 1 or now().weekday() == 0 }}"
     # Create a fulle backup with a name like "Full Backup 2022-12-31 08:45:00"
     action:
       - service: hassio.backup_full
         data:
           name: "{{ now().timestamp() | timestamp_custom("Full Backup %Y-%M-%d %H-%M-%S") }}"
           password: "your backup password, or omit if you don't use one"
     mode: single
     ```
     On any day the automation creates a backup, the addon will see the full backup already created (or get blocked until it completes) and assume that should be the backup for the day.  You can use this technique to create any kind of backup strategy that you can express in Home Assistant's templating engine and just use the addon to handling managing generational deletes.  The only real downside is that if the backup fails for some reason, the automation won't retry it.
