### ISSUE TITLE
Notify on telegram

### ISSUE THREAD

**Issue by matteo289** [sabeechen/hassio-google-drive-backup#797]
Hi
I would like to know if there is the possibility to send a notification on telegram only when the backup is done correctly.
Now the sensor.backup_state entity has the value "backed_up" , so my automation sends a notification even when the backup is not started (I do it every 3 days).
Is it possible to modify the value of "sensor.backup_state" with a template?

Thank you

**Comment by sabeechen** [comment]
Its a little tricky, but you can create some templates to do this:
First, make a sensor that exposes the latest backup date:
```yaml
template:
 - sensor:
     - name: "Latest Backup Date"
       device_class: timestamp
       state: >-
         {% if state_attr('sensor.backup_state', 'backups') %}
           {% set found=namespace(snapshot=None,time=0) %}
           {% for snapshot in state_attr('sensor.backup_state', 'backups') %}
             {% if as_timestamp(snapshot.date) > found.time and snapshot.state == "Backed Up" %}
               {% set found.time = as_timestamp(snapshot.date) %}
               {% set found.snapshot = snapshot %}
             {% endif %}
           {% endfor %}
           {% if found.snapshot %}
             {{ found.snapshot.date }}
           {% else %}
             unavailable
           {% endif %}
         {% else %}
           unavailable
         {% endif %}
````
Its more complicated than a normal sensor because it has to handle the sensor being unavailable an HA restart.

Then make an automation that triggers when the latest backup date changes:
```yaml
description: "Notify when a new backup is uploaded"
mode: single
trigger:
- platform: state
  entity_id: sensor.latest_backup_date
  not_from:
    - "unknown"
    - "unavailable"
condition: []
action:
  - service: notify.notify
    data:
      message: New Backup
      title: There is a new backup
```

You'd need to replace the action with whatever service you'd like to notify using.
