### ISSUE TITLE
Implement a companion integration that publishes sensors and notifications

### ISSUE THREAD

**Issue by Anto79-ops** [sabeechen/hassio-google-drive-backup#805]
Hi,

I reported an issue [here ](https://github.com/frenck/spook/issues/18)after using @frenck Spook integration, but turns out it found an issue with this addon.

long story short, you may wish to check out this thread.

thanks!

https://github.com/frenck/spook/issues/18

**Comment by sabeechen** [comment]
Thanks for bringing that thread to my attention, the language there (abuse, inject) implies I'm doing something nefarious and I feel the need to defend my methods.  I'll post my counter-rant there.

The "ghost" entities are something I'm aware of, but haven't had time to fix in light of other issues.  People get a degraded experience with the entities this addon creates.  They can't be customized and automations that reference them fail at startup because they don't exits until the addon republishes them (usually on a timer).  As pointed out it would be better to have a companion integration installed in Home Assistant, I just need to find the time.
In the meantime, there is a workaround if you don't like the errors spook is showing.  You can:
1. In the addon settings, uncheck "Enable Backup Staleness Sensor" and "Enable Backup State Sensor".   This will make the addon stop calling Home Assistant's /api/states/ API.
2. You can then create a template to call the addon directly to get the staleness.  For example the config below will create a rest binary sensor that queries the addon directly over docker's internal network to get the most recent backup date in Google Drive and check it isn't more than 30 hours old (24 hours plus a buffer):
``` yaml
binary_sensor:
  - platform: rest
    resource: http://cebe7a76-hassio-google-drive-backup:8099/getstatus
    name: Backups Stale But Better
    value_template: "{{ (now() - as_datetime(value_json.Sources.GoogleDrive.latest)) > timedelta(hours=30)}}"
    device_class: problem
```
The ```/getstatus``` endpoint there isn't exactly intended for people to query, but using it this way is unlikely to break in the future.  It might though.

**Comment by sabeechen** [comment]
Lets make this the official issue to implement a companion integration in Home Assistant to support the addon.  The goals would:

- Create a HA integration that handles the lifecycle for:
  - The binary_sensor.backups_stale sensor
  - The sensor.backup_state sensor
  - The persistent notification that pops up when backups are stale
- Provide an upgrade path for existing users that either:
  - Installs the companion silently in the background (not sure if this possible or even acceptable)
  - Prompts users to install the integration separately (and continues publishing the old way in the background).

The idea would be to implement this in a way that doesn't break existing user's workflows even if they silently upgrade to a version aware of the companion integration.

**Comment by Anto79-ops** [comment]
thank you for this information!

You're addon is arguably the most important in HA, and glad its getting some friendly banter :)

**Comment by erkr** [comment]
Thanks for the great add on
Will apply the rest sensor solution

**Comment by erkr** [comment]
For those interested, This command line sensor creates a similar `sensor.backup_state`. Besides the backup list, it filters out the 
Home assistant and GoogleDrive summaries and error info:
```
command_line:
  - sensor:
      name: Backup State
      unique_id: backup_state
      command: >
        curl -s http://cebe7a76-hassio-google-drive-backup:8099/getstatus | jq '{ "sources": .sources, "backups": ([ .backups[] | {"name": .name, "size": .size, "status": .status, "date": .date}] | sort_by(.date) | reverse), "last_error": {"count": .last_error_count, "message": .last_error} }' 
      value_template: >
        {{ 'Ok' if (value_json.last_error.count == 0 and 
                      (now() - as_datetime(value_json.sources.GoogleDrive.latest)) < timedelta(days=3, hours=6))
            else value_json.last_error.count~' errors' }}
      json_attributes:
        - sources
        - backups
        - last_error
      scan_interval: 3600  
```
