### ISSUE TITLE
Limit daily backups on Google drive

### ISSUE THREAD

**Issue by nsleigh** [sabeechen/hassio-google-drive-backup#827]
I was wondering if it is possible to limit the number of daily backups that go to Google drive independently of the total? The issue I am trying to solve is that I have 15Gb of Google drive and with 1Gb per HA backup that limits me to about 12 (with a few other things in the drive) but I would like to keep 14 days of local daily backups but if I set the max backups to 12 I loose the generational backups. So it would be nice to say have 12 backups in total in Google but only 5 dailies so I keep the weekly/monthly/yearly.

Hope this make sense!

**Comment by sabeechen** [comment]
Sorry it took me a bit to get back to you.

I think I understand what you're saying.  You'd like to have a different generational setting in Google Drive vs Home Assistant.  In your example you'd like 5 days kept in Google Drive, 14 Ddays in Home Assistant, but everything else the same.  This isn't something I *intended* to support, but I think you could get that behavior with the settings below.  Lets say you want to store 5 days in Drive, 14 days in home assistant, "W" weeks in both, "M" months in both, and "Y" years in both.

```yaml
'Backups in Google Drive': 5 + M + W + Y
'Backups in Home Assistant': 14 + W + M + Y 
'Generational Days': 5
'Generational weeks': W
'Generational Months': M
'Generational Years': Y
'Purge Old Backups Early': Off
'Ignore Other Backups': On
```

This should work because when 'Purge Old Backups Early' is off it won't actually delete anything until you're over the allowed number of backups, and it will start deleting the oldest first, leaving the daily backups to be deleted last.  Since Home Assistant can keep more backups than are needed for the generational schedule, it will keep around more daily backups (the newest ones).
