### ISSUE TITLE
Feature Request: Multiple Backup Options

### ISSUE THREAD

**Issue by noxhirsch** [sabeechen/hassio-google-drive-backup#99]
At first: Thank you for this amazing Addon! 👍 
It would be great, if you could select two backup options. E.g. backup the core config every night - and make a complete snapshot once a week.
But I also know that this would be very complex - especially with selecting the right snapshots to delete.

**Comment by sabeechen** [comment]
Heh, I've wanted that too.  I'm always trying to find a balance between making the add-on flexible and understandable but one always comes at the cost of the other.  The reality is I think if I implemented this into the UI, it would be a real mess to make it work understandably with all the other exiting options.  

If you'd like to accomplish this yourself, you could configure the add-on to only sync snapshots to Drive (set "Days between snapshots" to 0 in the UI).  Then you could set up automations in Home Assistant to call hassio's full snapshot/partial snapshot services on a schedule of your choosing.  Your automations.yaml would look something like this:
```yaml
- alias: Full Snapshot
  trigger:
    # Add some trigger here
  action:
  - service: hassio.snapshot_full
    data_template:
      name: "Full Backup {{now()}}"
      
- alias: Config Snapshot
  trigger:
    # Add some trigger here
  action:
  - service: hassio.snapshot_partial
    data_template:
      name: "Config Backup {{now()}}"
      folders: 
      - homeassistant
```

The addon would still sync new snapshots into Drive and delete old ones, this config would just delegate the responsibility for creating new snapshots to Home Assistant's automations.
